home/urls.py
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from .views import pagina_inicial, deletar_item, CriarListaView, CriarAtividadeView, CriarTarefaView, atualizar_item, atualizar_conteudo
from .views import atualizar_dados, ordenar_itens
urlpatterns = [
    path('', pagina_inicial, name='pagina_inicial'),
    path('criar_lista/', CriarListaView.as_view(), name='criar_lista'),
    path('criar_atividade/', CriarAtividadeView.as_view(), name='criar_atividade'),
    path('criar_tarefa/' , CriarTarefaView.as_view(), name='criar_tarefa'), 
    path('deletar_item/', deletar_item, name='deletar_item'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('atualizar_item/', atualizar_item, name='atualizar_item'),
    path('atualizar_conteudo/', atualizar_conteudo, name='atualizar_conteudo'),
    path('atualizar_dados/<str:object_type>/<int:item_id>/', atualizar_dados, name='atualizar_dados'),
    path('ordenar_itens/', ordenar_itens, name='ordenar_itens'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taskpad_api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

urlpatterns = [
    path("",  include('home.urls')),
    path("admin/", admin.site.urls),
    path("auth/", include('usuarios.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/docs/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

atividade/models.py
from django.db import models
from lista.models import Lista
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

class Atividade(models.Model):

    CHOICES = (
        (1, 'Baixa'),
        (2, 'Média'),
        (3, 'Alta'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    lista = models.ForeignKey(Lista, on_delete=models.CASCADE, default=1)  # Chave estrangeira para Lista
    nome = models.CharField(max_length=100)
    descricao = models.TextField(null=True, blank=True)
    dataInicio = models.DateField(null=True, blank=True)
    dataFim = models.DateField(null=True, blank=True)
    status = models.BooleanField()
    prioridade = models.IntegerField(choices=CHOICES) #Aqui é IntegerField
    texto = RichTextField(null=True, blank=True)

    def __str__(self):
        return self.nome

home/models.py
from atividade.models import Atividade
from lista.models import Lista
from tarefa.models import Tarefa

lista/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Agora Lista, Atividade e Tarefa tem comportamentos quase iguais pois os mesmos podem ser editados como arquivos de texto
class Lista(models.Model):
    CHOICES = (
        (1, 'Baixa'),
        (2, 'Média'),
        (3, 'Alta'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nome = models.CharField(max_length=100)
    descricao = models.TextField(null=True, blank=True)
    dataInicio = models.DateField(null=True, blank=True)
    dataFim = models.DateField(null=True, blank=True)
    status = models.BooleanField(default=True)
    prioridade = models.IntegerField(choices=CHOICES) 
    texto = RichTextField(null=True, blank=True)
    
    def __str__(self):
        return self.nome
   

tarefa/models.py
from django.db import models
from atividade.models import Atividade
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

class Tarefa(models.Model):
    CHOICES = (
        (1, 'Baixa'),
        (2, 'Média'),
        (3, 'Alta'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    atividade = models.ForeignKey(Atividade, on_delete=models.CASCADE, default=1)  # Chave estrangeira para Atividade
    nome = models.CharField(max_length=100)
    descricao = models.TextField(null=True, blank=True)
    dataInicio = models.DateField(null=True, blank=True)
    dataFim = models.DateField(null=True, blank=True)
    status = models.BooleanField()
    prioridade = models.IntegerField(choices=CHOICES) 
    texto = RichTextField(null=True, blank=True)

    def __str__(self):
        return self.nome

home/forms.py
from django import forms
from ckeditor.fields import RichTextFormField
from lista.models import Lista 
from atividade.models import Atividade
from tarefa.models import Tarefa
from ckeditor.widgets import CKEditorWidget

class ListaForm(forms.ModelForm):
    class Meta:
        model = Lista
        fields = ['texto']
        widgets = {
            'texto': CKEditorWidget(),
        }
        

class AtividadeForm(forms.ModelForm):
    class Meta:
        model = Atividade
        fields = ['texto']
        widgets = {
            'texto': CKEditorWidget(),
        }
        
class TarefaForm(forms.ModelForm):
    class Meta:
        model = Tarefa
        fields = ['texto']
        widgets = {
            'texto': CKEditorWidget(),
        }

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.utils.dateparse import parse_date
from ckeditor.fields import RichTextFormField
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.views import APIView
from drf_spectacular.utils import extend_schema, OpenApiParameter
import logging
from lista.models import Lista
from atividade.models import Atividade
from tarefa.models import Tarefa
from .forms import ListaForm, AtividadeForm, TarefaForm
from django.views.decorators.csrf import csrf_protect
from docx import Document
from htmldocx import HtmlToDocx
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.core import serializers
from django.db.models import F, Case, When, Value, CharField, IntegerField

@login_required(login_url="/auth/login/")
def pagina_inicial(request):
    if request.user.is_authenticated:
        listas = Lista.objects.filter(user=request.user)
        atividades = Atividade.objects.filter(user=request.user)
        tarefas = Tarefa.objects.filter(user=request.user)
        texto_form = RichTextFormField()
        lista_form = ListaForm()
        atividade_form = AtividadeForm()
        tarefa_form = TarefaForm()

        return render(request, 'pagina_inicial.html', {
            'listas': listas,
            'atividades': atividades,
            'tarefas': tarefas,
            'lista_form': lista_form,
            'atividade_form': atividade_form,
            'tarefa_form': tarefa_form,
            'texto_form': texto_form, 
        })
    else:
        return HttpResponse('Você precisa estar logado')


def ordenar_itens(request):
    if request.method == 'POST':
        ordem = request.POST.get('ordenarPor')  # Obtém a opção selecionada no formulário
        print(ordem)

        listas = Lista.objects.filter(user=request.user)
        atividades = Atividade.objects.filter(user=request.user)
        tarefas = Tarefa.objects.filter(user=request.user)
        texto_form = RichTextFormField()
        lista_form = ListaForm()
        atividade_form = AtividadeForm()
        tarefa_form = TarefaForm()
        print(listas)
        # Adicione um campo virtual para ordenação
        if ordem == 'dataAsc':
            listas = sorted(listas, key=lambda x: x.dataInicio)
        elif ordem == 'dataDesc':
            listas = sorted(listas, key=lambda x: x.dataInicio, reverse=True)
        elif ordem == 'prioridadeAsc':
            listas = sorted(listas, key=lambda x: x.prioridade)
        elif ordem == 'prioridadeDesc':
            listas = sorted(listas, key=lambda x: x.prioridade, reverse=True)
        elif ordem == 'nomeAsc':
            listas = sorted(listas, key=lambda x: x.nome)
        elif ordem == 'nomeDesc':
            listas = sorted(listas, key=lambda x: x.nome, reverse=True)
        print('-------------------------------------------------------------------')
        print(listas)

        # Retorne apenas o conteúdo da div como resposta
        return render(request, 'listas.html', 
                    {'listas': listas, 
                    'atividades': atividades, 
                    'tarefas': tarefas,
                    'lista_form': lista_form,
                    'atividade_form': atividade_form,
                    'tarefa_form': tarefa_form,
                    'texto_form': texto_form, })
    return redirect('pagina_inicial')


@csrf_protect
def atualizar_conteudo(request):
    if request.method == "POST":
        object_type = request.POST.get('object_type')
        item_id = request.POST.get('object_id')
        conteudo_atividade = request.POST.get('conteudo_atividade')
        
        if object_type and item_id:
            if object_type == 'lista':
                obj = get_object_or_404(Lista, id=item_id)
                obj.texto = conteudo_atividade
                obj.save()
            elif object_type == 'atividade':
                obj = get_object_or_404(Atividade, id=item_id)
                obj.texto = conteudo_atividade
                obj.save()
            elif object_type == 'tarefa':
                obj = get_object_or_404(Tarefa, id=item_id)
                obj.texto = conteudo_atividade
                obj.save()

            # Se a exportação deve ser realizada
            exportar = request.POST.get('exportar')
            #print(exportar)
            if exportar == 'true':

                conteudo = obj.texto
                conteudo = processar_imagens_base64(conteudo) # chamando a função que fiz abaixo

                #print(obj.nome)
                #print(conteudo)
                nome_do_arquivo = f"{obj.nome}_exported.docx"

                #novo documento DOCX
                doc = Document()
                new_parser = HtmlToDocx()

                # conteúdo HTML p documento DOCX
                new_parser.add_html_to_document(conteudo, doc)

                # Salvar o documento DOCX em uma resposta HTTP para download
                response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.wordprocessingml.document')
                response['Content-Disposition'] = f'attachment; filename="{nome_do_arquivo}"'
                doc.save(response)

                return response
            
            return JsonResponse({'conteudo_atividade': obj.texto})

    return JsonResponse({'erro': 'Requisição inválida'})

# ----------------------------------------------------------------------
# Func para processar imagens em base64 que fiz nos documentos

import re
import base64
import tempfile

def processar_imagens_base64(conteudo_html):
    # Expressão regular para encontrar imagens em Base64 no conteúdo HTML
    padrao_img = r'<img .*?src="data:image\/(\w+);base64,([^"]+)"'
    matches = re.findall(padrao_img, conteudo_html)

    for formato, match in matches:
        imagem_binaria = base64.b64decode(match)

        # Determinar a extensão do arquivo com base no formato
        if formato == 'jpeg':
            extensao = 'jpg'
        elif formato == 'png':
            extensao = 'png'
        elif formato == 'gif':
            extensao = 'gif'
        else:
            # tratar outros formatos aqui
            extensao = 'jpg'

        # Salvando a imagem como um arquivo temporário
        with tempfile.NamedTemporaryFile(delete=False, suffix=f'.{extensao}') as tmpfile:
            tmpfile.write(imagem_binaria)
            caminho_imagem_temporaria = tmpfile.name

        # Substitui a imagem pelo caminho do arquivo temporário no conteúdo HTML
        conteudo_html = conteudo_html.replace(f'data:image/{formato};base64,{match}', caminho_imagem_temporaria)

    return conteudo_html


# ----------------------------------------------------------------------
class CriarListaView(APIView):
    @extend_schema(
        description="Cria uma nova lista.",
        request=ListaForm,
        responses={201: "Objeto JSON contendo informações da nova lista criada."}
    )
    def post(self, request):
        nome_lista = request.data.get('nome')
        descricao = request.data.get('descricao')
        dataInicio = request.data.get('dataInicio')
        dataFim = request.data.get('dataFim')
        prioridade = request.data.get('prioridade')
        status = request.data.get('status')
        
        status = True if status == 'on' else False
        
        user = request.user

        if dataInicio:
            dataInicio = parse_date(dataInicio)
        else:
            dataInicio = None
        
        if dataFim:
            dataFim = parse_date(dataFim)
        else:
            dataFim = None

        nova_lista = Lista(
            user=user,
            nome=nome_lista,
            descricao=descricao,
            dataInicio=dataInicio,
            dataFim=dataFim,
            prioridade=prioridade,
            status=status
        )
        nova_lista.save()

        return redirect('pagina_inicial')

class CriarAtividadeView(APIView):
    @extend_schema(
        description="Cria uma nova atividade.",
        request=AtividadeForm,
        responses={201: "Objeto JSON contendo informações da nova atividade criada."}
    )
    def post(self, request):
        user = request.user
        lista_id = request.data.get('lista_id')
        nome_atividade = request.data.get('nome_atividade')
        descricao = request.data.get('descricao')
        dataInicio = request.data.get('dataInicio')
        dataFim = request.data.get('dataFim')
        status = request.data.get('status')
        prioridade = request.data.get('prioridade')

        status = True if status == 'on' else False
        
        if dataInicio:
            dataInicio = parse_date(dataInicio)
        else:
            dataInicio = None
        
        if dataFim:
            dataFim = parse_date(dataFim)
        else:
            dataFim = None

        nova_atividade = Atividade(
            user=user,
            lista_id=lista_id,
            nome=nome_atividade,
            descricao=descricao,
            dataInicio=dataInicio,
            dataFim=dataFim,
            status=status,
            prioridade=prioridade
        )
        nova_atividade.save()

        return redirect('pagina_inicial')

class CriarTarefaView(APIView):
    @extend_schema(
        description="Cria uma nova tarefa.",
        request=TarefaForm,
        responses={201: "Objeto JSON contendo informações da nova tarefa criada."}
    )
    def post(self, request):
        user = request.user
        atividade_id = request.data.get('atividade_id')
        nome_tarefa = request.data.get('nome_tarefa')
        descricao = request.data.get('descricao')
        dataInicio = request.data.get('dataInicio')
        dataFim = request.data.get('dataFim')
        status = request.data.get('status')

home/templates/listas.html
{% load static %}

<div class="bg-claro_style p-3 rounded max-height-list" style="text-align: left;">
    <!--   CONTINUAÇÃO   -->
    <div class="align-content">
        <div class="list-group col-md-12 ">
            {% for lista in listas %}
            <!-- Butoes de listas -->
            <div class="row">
                <div class="col-md-2 setinha" style="padding-right: 0%;">
                    <button class="com-borda list-group-item list-group-item-action pastel-button2a border-end-0"
                        data-bs-toggle="collapse" data-bs-target="#lista{{ lista.id }}">
                        <img src="{% static 'home/templates/ico-open.png' %}" alt="Ícone de Abrir"
                            style="max-width: 15px; max-height: 40px; flex-direction: column; justify-content: center; align-items: center;">
                    </button>
                </div>
                <div class="col-md-10" style="padding-left: 0%;">
                    <button class="overflow itemobjeto list-group-item list-group-item-action pastel-button2 border-start-0"
                        data-conteudo="{{ lista.texto }}" data-item-id="{{ lista.id }}" data-object-type="lista"
                        onclick="marcarListaAbertarow(this.parentElement.parentElement)"
                        data-nome-tarefa="{{ lista.nome }}" data-descricao="{{ lista.descricao }}"
                        data-ordem="{{ forloop.counter }}" data-data-inicio="{{ lista.dataInicio }}"
                        data-data-fim="{{ lista.dataFim }}" data-prioridade="{{ lista.prioridade }}">
                        <span
                            class="prioridade-indicador {% if lista.prioridade == 1 %}verde{% elif lista.prioridade == 2 %}amarelo{% else %}vermelho{% endif %}"></span>
                        {{ lista.nome }}
                    </button>
                </div>
            </div>

            <div id="lista{{ lista.id }}" class="collapse">
                <div class="list-group">
                    {% for atividade in lista.atividade_set.all %}

                    <div class="row">
                        <div class="col-md-2 setinha" style="padding-right: 0%;">
                            <button
                                class="com-borda list-group-item list-group-item-action pastel-button3a border-end-0"
                                data-bs-toggle="collapse" data-bs-target="#atividade{{ atividade.id }}">
                                <img src="{% static 'home/templates/ico-open.png' %}" alt="Ícone de Abrir"
                                    style="max-width: 15px; max-height: 20px;flex-direction: column;justify-content:center;align-items:center;">
                            </button>
                        </div>
                        <div class="col-md-10" style="padding-left: 0%;">
                            <!-- BOTEI NOME TAREFA LA EMBAIXO AGORA VAI FICAR NOME TAREFA EM TODOS -->
                            <button
                                class="overflow itemobjeto list-group-item list-group-item-action pastel-button3 border-start-0"
                                data-conteudo="{{ atividade.texto }}" data-item-id="{{ atividade.id }}"
                                data-object-type="atividade" data-nome-tarefa="{{ atividade.nome }}"
                                data-descricao="{{ atividade.descricao }}" data-data-inicio="{{ atividade.dataInicio }}"
                                data-data-fim="{{ atividade.dataFim }}" data-prioridade="{{ atividade.prioridade }}"
                                data-ordem="{{ forloop.counter }}"
                                onclick="marcarListaAbertarow(this.parentElement.parentElement)">
                                <span
                                    class="prioridade-indicador {% if atividade.prioridade == 1 %}verde{% elif atividade.prioridade == 2 %}amarelo{% else %}vermelho{% endif %}"></span>
                                {{ atividade.nome }}
                            </button>
                        </div>
                    </div>

                    <div id="atividade{{ atividade.id }}" class="collapse">
                        <div class="list-group">

                            {% for tarefa in atividade.tarefa_set.all %}
                            <div class="row">
                                <div class="col-md-12">
                                    <button
                                        class="itemobjeto com-borda list-group-item list-group-item-action pastel-button4"
                                        data-conteudo="{{ tarefa.texto }}" data-item-id="{{ tarefa.id }}"
                                        data-object-type="tarefa" data-nome-tarefa="{{ tarefa.nome }}"
                                        data-descricao="{{ tarefa.descricao }}"
                                        data-data-inicio="{{ tarefa.dataInicio }}" data-data-fim="{{ tarefa.dataFim }}"
                                        data-prioridade="{{ tarefa.prioridade }}" data-ordem="{{ forloop.counter }}"
                                        onclick="marcarListaAbertarow(this.parentElement.parentElement)">
                                        <span
                                            class="prioridade-indicador {% if tarefa.prioridade == 1 %}verde{% elif tarefa.prioridade == 2 %}amarelo{% else %}vermelho{% endif %}"></span>
                                        {{ tarefa.nome }}
                                    </button>
                                </div>
                            </div>
                            {% endfor %}

                            <button class="btn-criar btn btn-criar-tarefa pastel-button"
                                data-atividade-id="{{ atividade.id }}" data-bs-toggle="modal"
                                data-bs-target="#criarTarefaModal">
                                Criar Tarefa
                            </button>
                        </div>
                    </div>
                    {% endfor %}
                    <button class="btn-criar btn btn-criar-atividade pastel-button" data-lista-id="{{ lista.id }}"
                        data-bs-toggle="modal" data-bs-target="#criarAtividadeModal">
                        Criar Atividade
                    </button>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

home/templates/pagina_inicial.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <script src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Taskpad</title>
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'home/templates/style.css' %}">
    <!-- link para o CSS do Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Fonte Awesome sla mano to com sono -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        crossorigin="anonymous">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <!-- FULL CALENDAR-->
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js'></script>

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'home/templates/favicon.ico' %}">

    <!-- jquery? -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script src="https://kit.fontawesome.com/a994b9db28.js" crossorigin="anonymous"></script>



</head>

<body>
    <!-- Div com um Logout e logo -->
    <div class="row w-100" style="margin-left: 2%;">
        <div class="bg-claro_style d-flex justify-content-between align-items-center rounded">
            <div class="bg-cinza_style rounded">
                <h3 style="color: rgb(150, 90, 206);" class="texto-contorno">Taskpad</h3>
            </div>
            <div class="d-flex align-items-center">

                <button type="button" onclick="mostrarDiv(this)" class="btn">
                    <img src="{% static 'home/templates/calendarioroxo.png' %}" alt="Ícone de Calendário"
                        class="icone-grande">
                </button>

                <div class="btn-group">
                    <button type="button" class="btn " data-bs-toggle="dropdown" aria-expanded="false">
                        <div class="user-avatar">{{ request.user.username|first|upper }}</div>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <!-- <li><span class="dropdown-item-text">Bem-vindo, {{ request.user.username }}</span></li> -->
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


    <div class="row w-100" style="margin-left: 0px !important; margin-right: 0px !important; flex-wrap: nowrap;">


        <!---      DIV DAS LISTAS         -->
        <div class="col-md-2 bg-claro_style" style="margin: 1%; flex-direction: column; min-height: 85vh;">

            <!--full-height-row-->
            <div class="bg-claro_style p-3 rounded " style="text-align: left;">

                <!-- CAIXA DE PESQUISA-->
                <div class="col-md-12" style="margin: 2%; margin-bottom: 6%;">
                    <input type="text" id="searchInput" class="form-control"
                        placeholder="Buscar lista, atividade ou tarefa.">
                </div>

                <!-- TITULO -->
                <div class="lista-title">
                    <h4 style="text-align: center; font-size:17px;">LISTAS DE ATIVIDADES</h4>
                </div>
                <div class="row align-content">
                    <div class="col-md-12">
                        <button type="button" class="btn-criar pastel-button btn col-md-12" data-bs-toggle="modal"
                            data-bs-target="#criarListaModal">
                            Criar Lista
                        </button>
                        <!-- Caixa de seleção para filtrar por critério -->
                        <form id="ordenarForm" method="post" action="{% url 'ordenar_itens' %}">
                            {% csrf_token %}
                            <div class="mb-3" style="margin-bottom: -20px !important; margin-top: 2%;">
                                <select class="form-select" name="ordenarPor" id="ordenarPor">
                                    <option value="semOrdem" {% if ordem == 'semOrdem' %}selected{% endif %}>Sem Ordem</option>
                                    <option value="dataAsc" {% if ordem == 'dataAsc' %}selected{% endif %}>Data (Crescente)</option>
                                    <option value="dataDesc" {% if ordem == 'dataDesc' %}selected{% endif %}>Data (Decrescente)</option>
                                    <option value="prioridadeAsc" {% if ordem == 'prioridadeAsc' %}selected{% endif %}>Prioridade (Crescente)</option>
                                    <option value="prioridadeDesc" {% if ordem == 'prioridadeDesc' %}selected{% endif %}>Prioridade (Decrescente)</option>
                                    <option value="nomeAsc" {% if ordem == 'nomeAsc' %}selected{% endif %}>Nome (Crescente)</option>
                                    <option value="nomeDesc" {% if ordem == 'nomeDesc' %}selected{% endif %}>Nome (Decrescente)</option>
                                </select>
                                
                            </div>
                        </form>

                        <!--  fim do botao de caixa de seleção -->
                    </div>
                </div>
            </div>
            {% include 'modals.html' %}
            <div id='lista-itens' >
            {% include 'listas.html' %}
            </div>
            <!-- Formulário para enviar dados de atualização -->
            <form id="updateForm" method="post" action="{% url 'atualizar_item' %}">
                {% csrf_token %}
                <input type="hidden" name="object_type" id="updateObjectTypeInput" value="">
                <input type="hidden" name="item_id" id="updateItemIdInput" value="">

            </form>

            <!-- para enviar os dados para excluir os itens -->
            <form id="deleteForm" method="post" action="{% url 'deletar_item' %}">
                {% csrf_token %}
                <input type="hidden" name="objectType" id="objectTypeInput">
                <input type="hidden" name="itemId" id="itemIdInput">
            </form>

        </div>

        <!-- CALENDARIO -->
        <div id="divCalendario" class="col-md-10 bg-claro_style"
            style="padding: 1%; margin-top: 1%; margin-bottom: 1%; display: none;">
            <div class="bloco-calendario">
                <div id="calendario" class="calendario-personalizado"></div>
            </div>
        </div>

        <!-- MENSAGEM DE BOAS VINDAS +--->

        <div id="boasVindas" class="col-md-10 bg-claro_style" style="padding: 1%; margin-top: 1%; margin-bottom: 1%;">
            <div>
                <div class="resumoDia">
                    Seu resumo do dia <span id="dataAtual"></span>
                </div>
                <div class="boasVindas">
                    <h1>Ola, {{ request.user.username }}!</h1>
                    <p>Bem-vindo ao Taskpad! Selecione um item para começar a editar.</p>
                    <p style="margin-bottom: 5%;">Clique em "Criar Lista" para criar uma nova Lista de Atividades.</p>
                    <img src="{% static 'home/templates/escrevendo-branco.png' %}"
                        style="max-width: 150px; max-height: 150px;" alt="Imagem de lista">
                </div>
            </div>
        </div>


        <!-- Forms, ISSO AQUI É O FORMS DO EDITOR CKEDITOR "TEXTAREA" -->

        <div class="col-md-10 " style="padding-top: 1%; display: none;" id="ckeditor-id">

            <form method="post" action="{% url 'atualizar_conteudo' %}" id="meuFormulario"
                class="bg-claro_style p-3 rounded" style="flex-direction: column; min-height: 85vh;">
                {% csrf_token %}

                <!-- Formulário para criar uma nova lista -->
                <input type="hidden" id="item_id" name="object_id">
                <input type="hidden" id="object_type" name="object_type">
                <!-- Campo oculto para o tipo de objeto -->
                <div style="margin-left: 2cm; margin-right: 2cm;">
                    <textarea id="conteudo_atividade" name="conteudo_atividade" style="display: none;"></textarea>
                </div>

                <!-- Botão de envio do formulário -->
                <button type="button" class="btn salvar-button" id="atualizarConteudo">Salvar</button>

                <input type="hidden" name="exportar" id="exportar" value="false">
                <button type="button" class="btn exportar-botao" id="exportar-botao">
                    Exportar
                    <img src="{% static 'home/templates/arquivo-docx.png' %}" alt="Ícone de Calendário"
                        style="width: 25px;">
                </button>
            </form>

        </div>

    </div>
    <!-- outros conteúdos da página -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Scripts JS-->
    <script src="{% static 'home/templates/pagina_inicial.js' %}"></script>

</body>

</html>